name: build code 

## speciy the event triggers 
on:
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
    
  job1:
    runs-on: ubuntu-latest  
    steps:
      - name: create a file on the runner
        run: mkdir xashybatch5   
      - name: display this command 
        run: echo "we are learning github action"
